module ActiveAdmin
  def self.before_load: () { (ActiveAdmin::Application) -> void } -> void

  class Application
    def comments_menu=: (Hash[Symbol, untyped] | nil) -> void
    def namespace: (Symbol) { (untyped) -> void } -> void
  end
end
