module ActiveAdmin
  # ActiveAdmin::MenuTree class
  module MenuTree
    class Error < StandardError
    end

    include ActiveAdmin::MenuTree::Logging

    def self.setup: () { (Config) -> void } -> void

    def self.config: () -> Config

    private

    def self.setup_menu_options: (ActiveAdmin::Application) -> void
  end
end
