activeadmin:
  menu_tree:
    - id: Dashboard
    - id: Product
    - label: User Info
      children:
        - id: User
        - id: Profile
    - label: Admin
      children:
        - id: AdminUser
          label: Admin Users
        - id: Comment
          label: Admin Comments
          url: /admin/comments
    - label: Others
      children:
        - id: Foo
        - id: Bar
        - label: Baz
          url: 'https://example.com/baz'
          html_options:
            target: blank
        - id: ほげ
    - label: Lorem
      children:
        - label: ipsum
          children:
            - label: dolor
              children:
                - label: sit
                  children:
                    - label: amet
                      url: 'https://wikipedia.org/wiki/Lorem_ipsum'
                      html_options:
                        target: blank
    - label: Example Site
      url: 'https://example.com'
      html_options:
        target: blank
