module ActiveAdmin::MenuTree
  # ActiveAdmin::MenuTree::Config class
  class Config
    type menu_tree_item = Hash[Symbol, untyped]
    type menu_option = Hash[Symbol, untyped]

    attr_reader menu_tree: Array[menu_tree_item]
    attr_reader menu_options: Array[menu_option]

    def initialize: () -> void

    # def menu_tree=: (Array[Hash[untyped, untyped]] new_value) -> void
    def menu_tree=: (Array[untyped] new_value) -> void

    def find_menu_option: (id: String) -> (menu_option | nil)

    private

    def flatten_options: (untyped items, ?parent: untyped? parent) -> Array[menu_option]

    def format_options: (Hash[Symbol, untyped] item, index: Integer index, ?parent: String? parent) -> menu_option
  end
end
