module ActiveAdmin::MenuTree
  class Config
    attr_reader menu_tree: Array[Hash[Symbol, untyped]]
    attr_reader menu_options: Array[Hash[Symbol, untyped]]

    def initialize: () -> void

    # def menu_tree=: (Array[Hash[untyped, untyped]] new_value) -> void
    def menu_tree=: (Array[untyped] new_value) -> void

    def find_menu_option: (name: String) -> (Hash[Symbol, untyped] | nil)

    private

    def flatten_menu_tree: () -> Array[Hash[Symbol, untyped]]

    def format_options: (Hash[Symbol, untyped] item, index: Integer index, ?parent: String? parent) -> Hash[Symbol, untyped]
  end
end
