module ActiveAdmin::MenuTree
  class Config
    attr_reader menu_tree: untyped

    attr_reader menu_options: untyped

    def initialize: () -> untyped

    def menu_tree=: (untyped new_value) -> untyped

    def find_menu_option: (name: untyped name) -> untyped

    private

    def flatten_menu_tree: () -> untyped

    def format_options: (untyped item, index: untyped index, ?parent: untyped? parent) -> untyped
  end
end
