name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install bundler
        run: gem install bundler
      - name: Setup
        run: bin/setup
      - name: Rubocop
        run: bundle exec rake rubocop
  # steep:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 3.1
  #     - name: Install bundler
  #       run: gem install bundler
  #     - name: Setup
  #       run: bin/setup
  #     - name: Steep
  #       run: bundle exec steep check
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7
          - 3.0
          - 3.1
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install bundler
        run: gem install bundler
      - name: Setup
        run: bin/setup
      - name: RSpec
        run: bundle exec rake spec
