name: Ruby

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Install bundler
      run: gem install bundler
    - name: Setup
      run: bin/setup
    - name: Rubocop
      run: bundle exec rake rubocop
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Install bundler
      run: gem install bundler
    - name: Setup
      run: bin/setup
    - name: RSpec
      run: bundle exec rake spec
